import BinarySearchTree
q = BinarySearchTree()

# Need to do add function
q.add(3, "third")
q.add(2, "second")
q.add(1, "first")
print(q.find(2.5))
q.remove(3)
print(q.find(3))
q.add(3, "third")
q.add(5, "fifth")
q.add(4, "fourth")
print(q.find_eq(3.4))
print(q.find(3.4))
print("In order")
q.in_order()
print("Pre oder")
q.pre_order()
print("Pos order")
q.pos_order()
